const listWithOneBlog = [
  {
    _id: '5a422aa71b54a676234d17f8',
    title: 'Go To Statement Considered Harmful',
    author: 'Edsger W. Dijkstra',
    url: 'http://www.u.arizona.edu/~rubinson/copyright_violations/Go_To_Considered_Harmful.html',
    likes: 5,
    __v: 0,
  },
];

const listWithTwoBlogs = [
  {
    _id: '5a422aa71b54a676234d17f8',
    title: 'Go To Statement Considered Harmful',
    author: 'Edsger W. Dijkstra',
    url: 'http://www.u.arizona.edu/~rubinson/copyright_violations/Go_To_Considered_Harmful.html',
    likes: 5,
    __v: 0,
  },
  {
    _id: '659966da68cd46aa8ff87a5a',
    title: 'Netflix Tech Blog',
    author: 'Netflix',
    url: 'https://netflixtechblog.com/',
    likes: 4,
    __v: 1,
  },
];

const listWithManyBlogs = [
  {
    _id: '5a422aa71b54a676234d17f8',
    title: 'Go To Statement Considered Harmful',
    author: 'Edsger W. Dijkstra',
    url: 'http://www.u.arizona.edu/~rubinson/copyright_violations/Go_To_Considered_Harmful.html',
    likes: 5,
    __v: 0,
  },
  {
    _id: '659966da68cd46aa8ff87a5a',
    title: 'Netflix Tech Blog',
    author: 'Netflix',
    url: 'https://netflixtechblog.com/',
    likes: 4,
    __v: 1,
  },
  {
    _id: '5a422a851b54a676234d17f7',
    title: 'React patterns',
    author: 'Michael Chan',
    url: 'https://reactpatterns.com/',
    likes: 7,
    __v: 0,
  },
  {
    _id: '5a422b3a1b54a676234d17f9',
    title: 'Canonical string reduction',
    author: 'Edsger W. Dijkstra',
    url: 'http://www.cs.utexas.edu/~EWD/transcriptions/EWD08xx/EWD808.html',
    likes: 12,
    __v: 0,
  },
  {
    _id: '5a422b891b54a676234d17fa',
    title: 'First class tests',
    author: 'Robert C. Martin',
    url: 'http://blog.cleancoder.com/uncle-bob/2017/05/05/TestDefinitions.htmll',
    likes: 10,
    __v: 0,
  },
  {
    _id: '5a422ba71b54a676234d17fb',
    title: 'TDD harms architecture',
    author: 'Robert C. Martin',
    url: 'http://blog.cleancoder.com/uncle-bob/2017/03/03/TDD-Harms-Architecture.html',
    likes: 0,
    __v: 0,
  },
  {
    _id: '5a422bc61b54a676234d17fc',
    title: 'Type wars',
    author: 'Robert C. Martin',
    url: 'http://blog.cleancoder.com/uncle-bob/2016/05/01/TypeWars.html',
    likes: 2,
    __v: 0,
  },
  {
    title: 'The GitHub Blog',
    author: 'GitHub',
    url: 'https://github.blog/category/engineering/',
    likes: 150,
  },
  {
    title: 'PostgreSQL Blog',
    author: 'Crunchy Data',
    url: 'https://www.crunchydata.com/blog',
    likes: 75,
  },
  {
    title: 'The Asia-Pacific Journal: Japan Focus',
    author: 'Various',
    url: 'https://apjjf.org/',
    likes: 80,
  },
  {
    title: "Tae Kim's Guide to Learning Japaneses",
    author: 'Tae Kim',
    url: 'https://guidetojapanese.org/learn/category/blog/',
    likes: 200,
  },
];

const listWithTwoBlogsWithMaxLikes = [
  {
    _id: '5a422aa71b54a676234d17f8',
    title: 'Go To Statement Considered Harmful',
    author: 'Edsger W. Dijkstra',
    url: 'http://www.u.arizona.edu/~rubinson/copyright_violations/Go_To_Considered_Harmful.html',
    likes: 5,
    __v: 0,
  },
  {
    _id: '6599d7c54f2ee77652c9a6c9',
    title: 'A methodological remark on mathematical induction',
    author: 'Edsger W. Dijkstra',
    url: 'https://www.cs.utexas.edu/~EWD/ewd10xx/EWD1004.PDF',
    likes: 5,
    __v: 0,
  },
  {
    _id: '659966da68cd46aa8ff87a5a',
    title: 'Netflix Tech Blog',
    author: 'Netflix',
    url: 'https://netflixtechblog.com/',
    likes: 4,
    __v: 1,
  },
  {
    _id: '5a422a851b54a676234d17f7',
    title: 'React patterns',
    author: 'Michael Chan',
    url: 'https://reactpatterns.com/',
    likes: 7,
    __v: 0,
  },
  {
    _id: '5a422b3a1b54a676234d17f9',
    title: 'Canonical string reduction',
    author: 'Edsger W. Dijkstra',
    url: 'http://www.cs.utexas.edu/~EWD/transcriptions/EWD08xx/EWD808.html',
    likes: 200,
    __v: 0,
  },
  {
    _id: '5a422b891b54a676234d17fa',
    title: 'First class tests',
    author: 'Robert C. Martin',
    url: 'http://blog.cleancoder.com/uncle-bob/2017/05/05/TestDefinitions.htmll',
    likes: 10,
    __v: 0,
  },
  {
    _id: '5a422ba71b54a676234d17fb',
    title: 'TDD harms architecture',
    author: 'Robert C. Martin',
    url: 'http://blog.cleancoder.com/uncle-bob/2017/03/03/TDD-Harms-Architecture.html',
    likes: 0,
    __v: 0,
  },
  {
    _id: '5a422bc61b54a676234d17fc',
    title: 'Type wars',
    author: 'Robert C. Martin',
    url: 'http://blog.cleancoder.com/uncle-bob/2016/05/01/TypeWars.html',
    likes: 2,
    __v: 0,
  },
  {
    title: 'The GitHub Blog',
    author: 'GitHub',
    url: 'https://github.blog/category/engineering/',
    likes: 150,
  },
  {
    title: 'PostgreSQL Blog',
    author: 'Crunchy Data',
    url: 'https://www.crunchydata.com/blog',
    likes: 75,
  },
  {
    title: 'The Asia-Pacific Journal: Japan Focus',
    author: 'Various',
    url: 'https://apjjf.org/',
    likes: 80,
  },
  {
    title: "Tae Kim's Guide to Learning Japaneses",
    author: 'Tae Kim',
    url: 'https://guidetojapanese.org/learn/category/blog/',
    likes: 200,
  },
];

const listWhereAllAuthorsHaveTheSameTotalNumberOfLikesAcrossBlogs = [
  {
    _id: '5a422aa71b54a676234d17f8',
    title: 'Go To Statement Considered Harmful',
    author: 'Edsger W. Dijkstra',
    url: 'http://www.u.arizona.edu/~rubinson/copyright_violations/Go_To_Considered_Harmful.html',
    likes: 180,
    __v: 0,
  },
  {
    _id: '5a422b3a1b54a676234d17f9',
    title: 'Canonical string reduction',
    author: 'Edsger W. Dijkstra',
    url: 'http://www.cs.utexas.edu/~EWD/transcriptions/EWD08xx/EWD808.html',
    likes: 20,
    __v: 0,
  },
  {
    _id: '5a422b891b54a676234d17fa',
    title: 'First class tests',
    author: 'Robert C. Martin',
    url: 'http://blog.cleancoder.com/uncle-bob/2017/05/05/TestDefinitions.htmll',
    likes: 100,
    __v: 0,
  },
  {
    _id: '5a422ba71b54a676234d17fb',
    title: 'TDD harms architecture',
    author: 'Robert C. Martin',
    url: 'http://blog.cleancoder.com/uncle-bob/2017/03/03/TDD-Harms-Architecture.html',
    likes: 100,
    __v: 0,
  },
];

module.exports = {
  listWithOneBlog,
  listWithTwoBlogs,
  listWithManyBlogs,
  listWithTwoBlogsWithMaxLikes,
  listWhereAllAuthorsHaveTheSameTotalNumberOfLikesAcrossBlogs,
};
