DELETE http://localhost:3003/api/blogs/65f1adcefcd4441913e299c6
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QgcmVzdCB1c2VyIiwiaWQiOiI2NWYxYTYyNjFmZWFmYWQ0ZGViZTY0ZDEiLCJpYXQiOjE3MTAzMzc0NzAsImV4cCI6MTcxMDM0MTA3MH0.F0zfO4fgXTFrj2E1eujQn2Ugm7-b92YBsvBApMsEqkk