POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlNha2Ftb3RvIFJ5b3VtYSIsImlkIjoiNjVmMWE2MjgxZmVhZmFkNGRlYmU2NGQzIiwiaWF0IjoxNzEwMzM1NTM3LCJleHAiOjE3MTAzMzkxMzd9.F9yhbGMd76Wy7qL-2Zys3qaMR93U0YAPdVChf3Z0NT0

{
    "title": "Netflix Tech Blog",
    "author": "Netflix",
    "url": "https://netflixtechblog.com/",
    "likes": 50
}
###
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlNha2Ftb3RvIFJ5b3VtYSIsImlkIjoiNjVmMWE2MjgxZmVhZmFkNGRlYmU2NGQzIiwiaWF0IjoxNzEwMzM1NTM3LCJleHAiOjE3MTAzMzkxMzd9.F9yhbGMd76Wy7qL-2Zys3qaMR93U0YAPdVChf3Z0NT0

{
    "title": "The GitHub Blog",
    "author": "GitHub",
    "url": "https://github.blog/category/engineering/",
    "likes": 150
}
###
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlNha2Ftb3RvIFJ5b3VtYSIsImlkIjoiNjVmMWE2MjgxZmVhZmFkNGRlYmU2NGQzIiwiaWF0IjoxNzEwMzM1NTM3LCJleHAiOjE3MTAzMzkxMzd9.F9yhbGMd76Wy7qL-2Zys3qaMR93U0YAPdVChf3Z0NT0

{
    "title": "PostgreSQL Blog",
    "author": "Crunchy Data",
    "url": "https://www.crunchydata.com/blog",
    "likes": 75
}
###
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlNha2Ftb3RvIFJ5b3VtYSIsImlkIjoiNjVmMWE2MjgxZmVhZmFkNGRlYmU2NGQzIiwiaWF0IjoxNzEwMzM1NTM3LCJleHAiOjE3MTAzMzkxMzd9.F9yhbGMd76Wy7qL-2Zys3qaMR93U0YAPdVChf3Z0NT0

{
    "title": "The Asia-Pacific Journal: Japan Focus",
    "author": "Various",
    "url": "https://apjjf.org/",
    "likes": 80
}



###
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QgcmVzdCB1c2VyIiwiaWQiOiI2NWYxYTYyNjFmZWFmYWQ0ZGViZTY0ZDEiLCJpYXQiOjE3MTAzMzU2MDgsImV4cCI6MTcxMDMzOTIwOH0.MA_3SO_MSEWuXZCMp4v72aK4lXpumDpqECD2E3Lp9gU

{
    "title": "Tae Kim's Guide to Learning Japaneses",
    "author": "Tae Kim",
    "url": "https://guidetojapanese.org/learn/category/blog/",
    "likes": 200
}
###
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QgcmVzdCB1c2VyIiwiaWQiOiI2NWYxYTYyNjFmZWFmYWQ0ZGViZTY0ZDEiLCJpYXQiOjE3MTAzMzU2MDgsImV4cCI6MTcxMDMzOTIwOH0.MA_3SO_MSEWuXZCMp4v72aK4lXpumDpqECD2E3Lp9gU

{
    "title": "A methodological remark on mathematical induction",
    "author": "Edsger W. Dijkstra",
    "url": "https://www.cs.utexas.edu/~EWD/ewd10xx/EWD1004.PDF",
    "likes": 5
}
###
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QgcmVzdCB1c2VyIiwiaWQiOiI2NWYxYTYyNjFmZWFmYWQ0ZGViZTY0ZDEiLCJpYXQiOjE3MTAzMzU2MDgsImV4cCI6MTcxMDMzOTIwOH0.MA_3SO_MSEWuXZCMp4v72aK4lXpumDpqECD2E3Lp9gU

{
    "title": "Has silver's place in China's fiscal and monetary system been overestimated?",
    "author": "Junyi Jiang",
    "url": "https://blogs.lse.ac.uk/economichistory/2023/11/24/has-silvers-place-in-chinas-fiscal-and-monetary-system-been-overestimated/",
    "likes": 4
}
###
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QgcmVzdCB1c2VyIiwiaWQiOiI2NWYxYTYyNjFmZWFmYWQ0ZGViZTY0ZDEiLCJpYXQiOjE3MTAzMzk5MzgsImV4cCI6MTcxMDM0MzUzOH0.6z8uEAV2NKwtA4yfyrXN9VbYya_R8pBk2DJCERRz7KA

{
    "title": "Has China always been ruled by a Han elite?",
    "author": "Yitong Qiu",
    "url": "https://blogs.lse.ac.uk/economichistory/2022/11/11/has-china-always-been-ruled-by-a-han-elite/",
    "likes": 6
}
###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "No json web token and should be rejected by server",
    "author": "No jwt",
    "url": "https://why.is/there-no-jwt",
    "likes": 0
}