DELETE http://localhost:3003/api/blogs/65f1b79cc2397e5c5af1bc08
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QgcmVzdCB1c2VyIiwiaWQiOiI2NWYxYTYyNjFmZWFmYWQ0ZGViZTY0ZDEiLCJpYXQiOjE3MTAzMzk5MzgsImV4cCI6MTcxMDM0MzUzOH0.6z8uEAV2NKwtA4yfyrXN9VbYya_R8pBk2DJCERRz7K