POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Netflix Tech Blog",
    "author": "Netflix",
    "url": "https://netflixtechblog.com/",
    "likes": 50
}
###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "The GitHub Blog",
    "author": "GitHub",
    "url": "https://github.blog/category/engineering/",
    "likes": 150
}
###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "PostgreSQL Blog",
    "author": "Crunchy Data",
    "url": "https://www.crunchydata.com/blog",
    "likes": 75
}
###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "The Asia-Pacific Journal: Japan Focus",
    "author": "Various",
    "url": "https://apjjf.org/",
    "likes": 80
}
###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Tae Kim's Guide to Learning Japaneses",
    "author": "Tae Kim",
    "url": "https://guidetojapanese.org/learn/category/blog/",
    "likes": 200
}